# Generated by Django 2.1.2 on 2018-11-06 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EgoGridDing0VersioningTest',
            fields=[
                ('run_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=6000, null=True)),
            ],
            options={
                'db_table': 'ego_grid_ding0_versioning_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EgoGridDing0LvStationTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_db', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ego_grid_ding0_lv_station_test',
                'managed': False,
            },
        ),
    ]
