# Generated by Django 2.1.2 on 2018-11-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eGoVIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egogridding0lvstationtest',
            options={'managed': False, 'verbose_name_plural': 'lv_station'},
        ),
    ]
